# Kubernetes pod of nginx ......declarative way

apiVersion: v1
kind: Pod
metadata:
  name: nginx-declarative-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
